import csv
import random
import re

tech_templates = [
    "What is {} in {}?",
    "How to {} using {}?",
    "Explain the concept of {}.",
    "What is the difference between {} and {}?",
    "How does {} work?",
    "What are the best practices for {}?",
    "What is the use of {} in {}?",
    "Define {} and provide an example.",
    "What is the primary role of {} in a modern application?",
    "Why is {} considered essential for {}?",
    "In the context of {}, what does {} refer to?",
    "What problem does {} attempt to solve?",
    "Describe the architecture of {}.",
    "What is the standard protocol for {}?",
    "Contrast {} with {}.",
    "Under what conditions would you choose {} over {}?",
    "What are the pros and cons of using {} versus {}?",
    "Is {} a suitable replacement for {}?",
    "How does {}'s performance compare to that of {}?",
    "Differentiate between {} and {}.",
    "What are the similarities between {} and {}?",
    "How do you implement {} in {}?",
    "What are the steps involved in deploying a {}?",
    "Can you provide a code snippet for {}?",
    "What dependencies are needed to use {}?",
    "How to set up a basic {} project?",
    "What is the typical lifecycle of a {} object?",
    "Explain the methodology for creating {}.",
    "When should a developer use {}?",
    "Provide a real-world use case for {}.",
    "How is {} utilized in {}?",
    "What are the key features of {}?",
    "Name a major company that uses {}.",
    "How can {} improve the scalability of {}?",
    "What security implications does {} have?",
    "What are common errors encountered when using {}?",
    "How do you debug issues related to {}?",
    "What are the limitations of {}?",
    "How to handle a {} failure?",
    "What is the biggest challenge when working with {}?",
    "How can we optimize the performance of {}?",
    "Describe a scenario that leads to a {} conflict.",
    "What is the impact of {} on {} performance?",
    "Explain the mathematical foundation of {}.",
    "What is the current industry trend regarding {}?",
    "How is {} evolving in {}?",
    "Which license model is commonly associated with {}?",
    "What are the security best practices for {}?",
    "What is the theoretical maximum for {}?",
]

tech_keywords = [
    "polymorphism",
    "inheritance",
    "recursion",
    "multithreading",
    "data structure",
    "algorithm",
    "Big O",
    "linked list",
    "hash map",
    "binary tree",
    "stack",
    "queue",
    "garbage collection",
    "design pattern",
    "refactoring",
    "compiler",
    "interpreter",
    "virtual machine",
    "IDE",
    "lambda function",
    "closure",
    "memoization",
    "dynamic programming",
    "asynchronous",
    "synchronous",
    "exception handling",
    "type casting",
    "serialization",
    "deserialization",
    "generics",
    "interface",
    "abstract class",
    "SOLID principles",
    "Python",
    "Java",
    "JavaScript",
    "TypeScript",
    "C++",
    "Go",
    "Ruby",
    "C#",
    "Kotlin",
    "Swift",
    "Rust",
    "PHP",
    "HTML",
    "CSS",
    "React",
    "Node.js",
    "Angular",
    "Vue.js",
    "Django",
    "Flask",
    "Spring Boot",
    "Express.js",
    ".NET",
    "Redux",
    "SASS/LESS",
    "HTTP",
    "HTTPS",
    "API",
    "REST",
    "GraphQL",
    "frontend",
    "backend",
    "full stack",
    "CDN",
    "caching",
    "latency",
    "bandwidth",
    "DNS",
    "TCP/IP",
    "sockets",
    "OSI model",
    "router",
    "switch",
    "firewall",
    "VPN",
    "proxy server",
    "port",
    "IP address",
    "load balancer",
    "web server",
    "cookie",
    "session",
    "JWT",
    "cloud computing",
    "microservices",
    "monolith",
    "CI/CD",
    "Kubernetes",
    "DevOps",
    "Docker",
    "Git",
    "version control",
    "merge conflict",
    "Kubectl",
    "Helm",
    "Terraform",
    "Ansible",
    "Chef",
    "Jenkins",
    "GitLab CI",
    "GitHub Actions",
    "serverless",
    "Lambda",
    "SaaS",
    "PaaS",
    "IaaS",
    "virtualization",
    "VPC",
    "EC2",
    "S3",
    "Azure",
    "GCP",
    "monitoring",
    "logging",
    "telemetry",
    "database",
    "SQL",
    "NoSQL",
    "relational database",
    "document database",
    "graph database",
    "key-value store",
    "MongoDB",
    "PostgreSQL",
    "MySQL",
    "Redis",
    "indexing",
    "ACID properties",
    "CAP theorem",
    "data warehousing",
    "ETL",
    "data science",
    "Big Data",
    "Hadoop",
    "Spark",
    "data lake",
    "encryption",
    "hashing",
    "authentication",
    "authorization",
    "OAuth",
    "security patch",
    "vulnerability",
    "malware",
    "phishing",
    "DDoS",
    "TLS/SSL",
    "penetration testing",
    "zero trust",
    "MFA",
    "biometrics",
    "cryptocurrency",
    "blockchain",
    "smart contract",
    "digital signature",
    "XSS",
    "machine learning",
    "neural network",
    "deep learning",
    "model training",
    "bias",
    "regression",
    "classification",
    "clustering",
    "supervised learning",
    "unsupervised learning",
    "reinforcement learning",
    "feature engineering",
    "TensorFlow",
    "PyTorch",
    "NLP",
    "Computer Vision",
    "data set",
    "accuracy",
    "CPU",
    "RAM",
    "ROM",
    "GPU",
    "OS",
    "Linux",
    "Windows",
    "kernel",
    "shell script",
    "firmware",
    "memory management",
    "filesystem",
    "process",
    "thread",
    "device driver",
    "motherboard",
    "I/O",
    "storage",
    "Agile",
    "Scrum",
    "TDD",
    "unit testing",
    "integration testing",
    "acceptance testing",
    "waterfall model",
    "Kanban",
    "retrospective",
    "sprint",
    "JIRA",
    "Confluence",
    "requirements analysis",
    "UX/UI",
    "usability",
    "accessibility",
    "API gateway",
    "message queue",
    "event-driven architecture",
]

non_tech_templates = [
    "What is the capital of {}?",
    "Who wrote {}?",
    "When was {}?",
    "How to {}?",
    "Where is {} located?",
    "What are the benefits of {}?",
    "Who painted {}?",
    "Describe the primary characteristics of {}.",
    "What is the main ingredient in {}?",
    "What is the definition of {}?",
    "In mythology, who is the god/goddess of {}?",
    "What is the common symbolic meaning of {}?",
    "What is the classification or genus of {}?",
    "What is the highest-ranking official of {}?",
    "What was the main cause of {}?",
    "Who was the leader/figurehead during {}?",
    "In which year did {} end?",
    "What is the most famous event associated with {}?",
    "What treaty or agreement concluded {}?",
    "What major discovery is attributed to {}?",
    "How did {} influence modern {}?",
    "What genre of art/music is {}?",
    "Which museum houses {}?",
    "What are the key elements of the {} style?",
    "Name a famous work by {} (artist/author).",
    "What is the significance of {} in {} culture?",
    "What instrument is typically used to play {}?",
    "Who directed the film/play {}?",
    "What is the longest river in {}?",
    "What is the highest point in {}?",
    "What is the official currency of {}?",
    "Which ocean borders {}?",
    "What is the predominant climate in {}?",
    "What natural wonder is located near {}?",
    "Name a country that shares a border with {}.",
    "What is the first step in **baking** {}?",
    "What equipment is necessary for {}?",
    "How long does it take to complete {}?",
    "What is the recommended form for **meditation** while {}?",
    "What is the optimal temperature for storing {}?",
    "What are the rules of the sport/game {}?",
    "What is a popular variation of {}?",
    "How does {} differ from {}?",
    "Compare the political structure of {} and {}.",
    "What are the health risks associated with {}?",
    "What are the ethical considerations of {}?",
    "Which is older: {} or {}?",
    "What is the scientific name for {}?",
    "How many people speak {} (language)?",
]

non_tech_keywords = [
    "France",
    "1984",
    "the Mona Lisa",
    "meditation",
    "chocolate cake",
    "the first moon landing",
    "the Great Wall of China",
    "Albert Einstein",
    "Rome",
    "the Renaissance",
    "World War II",
    "baking bread",
    "swimming",
    "Ancient Egypt",
    "Cold War",
    "Industrial Revolution",
    "Magna Carta",
    "Suez Canal",
    "Vikings",
    "Feudalism",
    "democracy",
    "communism",
    "capitalism",
    "Brexit",
    "United Nations",
    "Treaty of Versailles",
    "Martin Luther King Jr.",
    "Nelson Mandela",
    "Queen Elizabeth II",
    "pyramids",
    "Spartacus",
    "Declaration of Independence",
    "civil rights",
    "Mayan civilization",
    "Inca empire",
    "Silk Road",
    "Ottoman Empire",
    "Mount Everest",
    "Amazon River",
    "Sahara Desert",
    "Great Barrier Reef",
    "Arctic Circle",
    "Tornado",
    "Volcano",
    "Earthquake",
    "Tsunami",
    "Pangaea",
    "ecosystem",
    "photosynthesis",
    "migration",
    "endangered species",
    "coral reef",
    "rainforest",
    "mountain range",
    "glacier",
    "equator",
    "latitude",
    "tectonic plates",
    "national park",
    "biodiversity",
    "Shakespeare",
    "Hamlet",
    "Picasso",
    "Impressionism",
    "Beethoven",
    "Symphony",
    "Opera",
    "Ballet",
    "poetry",
    "novel",
    "Existentialism",
    "Stoicism",
    "Socrates",
    "Plato",
    "Nietzsche",
    "Greek mythology",
    "Nordic mythology",
    "fairy tale",
    "sonnet",
    "abstract art",
    "Cubism",
    "Van Gogh",
    "The Scream",
    "monologue",
    "tragedy",
    "comedy",
    "manga",
    "cinema",
    "documentary",
    "Oscar award",
    "Nobel Prize",
    "Pulitzer Prize",
    "football (soccer)",
    "basketball",
    "tennis",
    "Marathon",
    "Olympics",
    "Yoga",
    "hiking",
    "Gardening",
    "Knitting",
    "Chess",
    "Poker",
    "Sailing",
    "Skiing",
    "Golf",
    "archery",
    "rock climbing",
    "tai chi",
    "jigsaw puzzle",
    "collecting stamps",
    "photography",
    "astronomy",
    "origami",
    "fencing",
    "judo",
    "camping",
    "birdwatching",
    "billiards",
    "pasta",
    "sushi",
    "Curry",
    "fermentation",
    "vegetarianism",
    "mediterranean diet",
    "vitamins",
    "protein",
    "carbohydrates",
    "metabolism",
    "blood pressure",
    "vaccination",
    "allergy",
    "sleep hygiene",
    "mindfulness",
    "etiquette",
    "public speaking",
    "negotiation",
    "time management",
    "financial literacy",
    "budgeting",
    "currency",
    "inflation",
    "stock market",
    "retirement plan",
    "journaling",
    "cooking",
    "recycling",
    "upcycling",
    "composting",
]


num_rows = 1000
data = []
placeholder_pattern = re.compile(r"\{\}")

for _ in range(num_rows):
    if random.random() < 0.5:
        template = random.choice(tech_templates)
        keywords = tech_keywords
        category = "Tech"
    else:
        template = random.choice(non_tech_templates)
        keywords = non_tech_keywords
        category = "Non-Tech"

    num_args = len(placeholder_pattern.findall(template))

    question = ""

    if num_args == 2:
        keyword1 = random.choice(keywords)
        keyword2 = random.choice(keywords)
        question = template.format(keyword1, keyword2)
    elif num_args == 1:
        keyword1 = random.choice(keywords)
        question = template.format(keyword1)
    else:
        continue

    data.append([question, category])

file_name = "tech_classification_large.csv"

try:
    with open(file_name, "w", newline="", encoding="utf-8") as f:
        writer = csv.writer(f)
        writer.writerow(["Question", "Category"])
        writer.writerows(data)

    print(f"CSV file with {len(data)} rows generated successfully: {file_name}")

except Exception as e:
    print(f"An error occurred during CSV file creation: {e}")

num_rows = 1000
data = []

for _ in range(num_rows):
    if random.random() < 0.5:
        template = random.choice(tech_templates)
        keyword1 = random.choice(tech_keywords)
        keyword2 = random.choice(tech_keywords)
        question = template.format(keyword1, keyword2)
        category = "Tech"
    else:
        template = random.choice(non_tech_templates)
        keyword = random.choice(non_tech_keywords)
        if "{}" in template and template.count("{}") == 2:
            keyword2 = random.choice(non_tech_keywords)
            question = template.format(keyword, keyword2)
        else:
            question = template.format(keyword)
        category = "Non-Tech"

    data.append([question, category])

with open(
    "../../data/raw/tech_classification.csv", "w", newline="", encoding="utf-8"
) as f:
    writer = csv.writer(f)
    writer.writerow(["Question", "Category"])
    writer.writerows(data)

print("CSV file with 1000 rows generated successfully!")
